# Generated by Django 3.2 on 2021-04-14 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CompanySwitches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, verbose_name='Ссылка')),
                ('price', models.IntegerField(verbose_name='Базовая цена')),
                ('desc_small', models.CharField(max_length=150, verbose_name='Короткое описание')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('main_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Основная фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('category_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
                ('company_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('color', models.CharField(max_length=10, verbose_name='Цвет')),
                ('company_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.companyswitches', verbose_name='Компания')),
            ],
        ),
        migrations.CreateModel(
            name='KeyboardSwitches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('item_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item', verbose_name='Клавиатура')),
                ('switch_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.switch', verbose_name='Переключатель')),
            ],
        ),
        migrations.CreateModel(
            name='ItemWithPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотография')),
                ('item_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Характеристика')),
                ('content', models.CharField(max_length=50, verbose_name='Значение')),
                ('item_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item', verbose_name='Товар')),
            ],
        ),
    ]
