# Generated by Django 3.2 on 2021-04-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyswitches',
            options={'ordering': ['title'], 'verbose_name': 'Компания Переключателей', 'verbose_name_plural': 'Компании Переключателей'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['company_fk'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='itemcharacteristic',
            options={'ordering': ['item_fk'], 'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='itemwithphoto',
            options={'ordering': ['item_fk'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='keyboardswitches',
            options={'ordering': ['item_fk'], 'verbose_name': 'Переключатель клавиатур', 'verbose_name_plural': 'Переключатели клавиатур'},
        ),
        migrations.AlterModelOptions(
            name='switch',
            options={'ordering': ['company_fk'], 'verbose_name': 'Переключатель', 'verbose_name_plural': 'Переключатели'},
        ),
        migrations.AlterField(
            model_name='item',
            name='desc_small',
            field=models.TextField(verbose_name='Короткое описание'),
        ),
    ]
