# Generated by Django 3.2 on 2021-04-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_switch_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/categories/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
